# -*- coding: utf-8 -*-
"""Copy of Day1assignmentds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQVsuJLB4-z99mBuIrN9Rwfbi6VgtAnp

CODES:-
# QUESTION 1
"""

a= "RANIBOW";
b= "RAINBOW";
c= "BOWRANI";
d= "ROWBANI";
 print("Given word is OBANWRI.\nselect correct English word \noptions: \n"+a+"\n"+b+"\n"+c+"\n"+d)
 
ans= input()
if (ans==b):
     print("CORRECT")
else:
     print("Wrong")

"""# QUESTION 2"""

print("LETS UPGRADE")

"""# QUESTION 3"""

cp= input()
sp= input()
 
 
if (sp>cp):
    print("PROFIT")
elif (sp<cp):
    print("LOSS")
elif (sp==cp):
    print("NEITHER")

"""# QUESTION 4"""

euros= int(input())
print(euros*80)
