# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1771i_uC21IeijnBKlodKMIYdgaV_jjc7

# Question 1
"""

lst=[]
print("enter numbers")
for i in range(10):
  num= int(input())
  if (num%2==0):
      lst.append(num)
print(lst)

"""# Question 3"""

d={}
n=int(input())
for i in range(1,n):
  d[i]= i*i
print(d)